objects/Form_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Page_Layout__c</fullName>
        <label>Reference Page Layout</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EDF Form Definition</label>
    <language>en_US</language>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>Form Definition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Form_Definition_Version__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Form_Definition__c</fullName>
        <label>Form Definition</label>
        <referenceTo>Form_Definition__c</referenceTo>
        <relationshipName>Form_Definition_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EDF Form Definition Version</label>
    <language>en_US</language>
    <nameField>
        <displayFormat>FDV-{0000}</displayFormat>
        <label>Form Definition Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Definition Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Form_Element__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>EDF Form Element</label>
    <language>en_US</language>
    <nameField>
        <displayFormat>FE-{0000}</displayFormat>
        <label>Form Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GenerateExtremeDynamicsFormsMetadataTest.cls
@isTest
private class GenerateExtremeDynamicsFormsMetadataTest {

    @TestSetup
    static void makeData(){

        Form_Definition__c fd = 
            new Form_Definition__c(
                    Object_API_Name__c = 'Form_Element__c',
                    Reference_Page_Layout__c = 'Form Element Layout'
                );
        insert fd;

        Form_Definition_Version__c fe =
            new Form_Definition_Version__c(
                    Form_Definition__c = fd.Id,
                    Active__c = true,
                    Short_Description__c = 'Form Version for Form_Element__c'
                );
        
        insert fe;
    }

    @isTest
    static void testCreateEDFMetadata(){

        Form_Definition_Version__c fdv = [Select 
                                            Id, 
                                            Form_Definition__r.Object_API_Name__c,
                                            Form_Definition__r.Reference_Page_Layout__c,
                                            Name 
                                            FROM Form_Definition_Version__c 
                                            LIMIT 1
                                        ];
        
        Test.startTest();

        GenerateExtremeDynamicsFormsMetadata.EDFMetadataRequest metadataReq = new GenerateExtremeDynamicsFormsMetadata.EDFMetadataRequest();
        metadataReq.formVersionId = fdv.Id;
        metadataReq.objectApiName = fdv.Form_Definition__r.Object_API_Name__c;
        metadataReq.pageLayout = fdv.Form_Definition__r.Reference_Page_Layout__c;
        
        List<GenerateExtremeDynamicsFormsMetadata.EDFMetadataResult> results =
            GenerateExtremeDynamicsFormsMetadata.createEDFMetadata(new List<GenerateExtremeDynamicsFormsMetadata.EDFMetadataRequest>{metadataReq});
        
        System.assert(results.size()>0);
        System.assertEquals(metadataReq.formVersionId,results[0].formVersionId);
        System.assertEquals(true,results[0].success);
        System.assertEquals('Metadata Created successfully',results[0].message);
        
        Test.stopTest();
    }

    @isTest
    static void testCreateEDFMetadataFail(){

        Form_Definition_Version__c fdv = [Select 
                                            Id, 
                                            Form_Definition__r.Object_API_Name__c,
                                            Form_Definition__r.Reference_Page_Layout__c,
                                            Name 
                                            FROM Form_Definition_Version__c 
                                            LIMIT 1
                                        ];
        
        Test.startTest();

        GenerateExtremeDynamicsFormsMetadata.EDFMetadataRequest metadataReq = new GenerateExtremeDynamicsFormsMetadata.EDFMetadataRequest();
        metadataReq.formVersionId = fdv.Id;
        metadataReq.objectApiName = fdv.Form_Definition__r.Object_API_Name__c;
        metadataReq.pageLayout = 'Dummy Page Layout';
        
        List<GenerateExtremeDynamicsFormsMetadata.EDFMetadataResult> results =
            GenerateExtremeDynamicsFormsMetadata.createEDFMetadata(new List<GenerateExtremeDynamicsFormsMetadata.EDFMetadataRequest>{metadataReq});
        
        System.assert(results.size()>0);
        System.assertEquals(metadataReq.formVersionId,results[0].formVersionId);
        System.assertEquals(false,results[0].success);
        System.assertEquals('Metadata creation failed. Reason: Invalid sObject and/or Reference Page Layout',results[0].message);
        
        Test.stopTest();
    }
    
}