objects/Form_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Page_Layout__c</fullName>
        <label>Reference Page Layout</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EDF Form Definition</label>
    <language>en_US</language>
    <nameField>
        <displayFormat>FD-{0000}</displayFormat>
        <label>Form Definition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Form_Definition_Version__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Form_Definition__c</fullName>
        <label>Form Definition</label>
        <referenceTo>Form_Definition__c</referenceTo>
        <relationshipName>Form_Definition_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EDF Form Definition Version</label>
    <language>en_US</language>
    <nameField>
        <displayFormat>FDV-{0000}</displayFormat>
        <label>Form Definition Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Definition Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Form_Element__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>EDF Form Element</label>
    <language>en_US</language>
    <nameField>
        <displayFormat>FE-{0000}</displayFormat>
        <label>Form Element Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExtremeDynamicFormsControllerTest.cls
@isTest
private class ExtremeDynamicFormsControllerTest {

    @TestSetup
    static void makeData(){

        Form_Definition__c fd = 
            new Form_Definition__c(
                    Object_API_Name__c = 'edf__Form_Element__c',
                    Reference_Page_Layout__c = 'Form Element Layout'
                );
        insert fd;

        Form_Definition_Version__c fdv =
            new Form_Definition_Version__c(
                    Form_Definition__c = fd.Id,
                    Active__c = true,
                    Short_Description__c = 'Form Version for edf__Form_Element__c'
                );
        
        insert fdv;

        
        GenerateExtremeDynamicsFormsMetadata.EDFMetadataRequest metadataReq = new GenerateExtremeDynamicsFormsMetadata.EDFMetadataRequest();
        metadataReq.formVersionId = fdv.Id;
        metadataReq.objectApiName = fd.Object_API_Name__c;
        metadataReq.pageLayout = fd.Reference_Page_Layout__c;
        
        GenerateExtremeDynamicsFormsMetadata.createEDFMetadata(new List<GenerateExtremeDynamicsFormsMetadata.EDFMetadataRequest>{metadataReq});
        
    }
    
    @isTest
    static void testGetFormMetadata(){

        Form_Definition_Version__c fdv = [Select Id, Name FROM Form_Definition_Version__c LIMIT 1];
        Form_Element__c feTheRecord = [Select Id FROM Form_Element__c LIMIT 1];

        Test.startTest();

        ExtremeDynamicFormsController.getFormMetadata(feTheRecord.Id, fdv.Name);

        Test.stopTest();
    }

    @isTest
    static void testGetFormMetadataIncompatibleFormVersion(){

        Form_Definition_Version__c fdv = [Select Id, Name FROM Form_Definition_Version__c LIMIT 1];
        
        Test.startTest();

        try{
            ExtremeDynamicFormsController.getFormMetadata(fdv.Id, fdv.Name);
        }catch(Exception e){
            System.assertEquals('Incompatible Form Version: '+fdv.Name+'. sObject on Form Defintion: edf__Form_Element__c is not same as record sObject: edf__Form_Definition_Version__c', e.getMessage());
        }

        Test.stopTest();
    }

    @isTest
    static void testGetFormMetadataInactiveFormVersion(){

        Form_Definition_Version__c fdv = [Select Id, Active__c, Name FROM Form_Definition_Version__c LIMIT 1];
        Form_Element__c feTheRecord = [Select Id FROM Form_Element__c LIMIT 1];

        fdv.Active__c = false;
        update fdv;

        
        Test.startTest();

        try{
            ExtremeDynamicFormsController.getFormMetadata(feTheRecord.Id, fdv.Name);
        }catch(Exception e){
            System.assertEquals('Could not find form version: '+fdv.Name+'. Its either deleted or not in Acive state', e.getMessage());
        }

        Test.stopTest();
    }

    @isTest
    static void testGetValues(){

        Test.startTest();

        ExtremeDynamicFormsController edfCtrlr = new ExtremeDynamicFormsController();
        VisualEditor.DynamicPickListRows myValues = edfCtrlr.getValues();

        System.assert(myValues!=null);

        Test.stopTest();

    }

    @isTest
    static void testGetDefaultValues(){

        Test.startTest();

        ExtremeDynamicFormsController edfCtrlr = new ExtremeDynamicFormsController();
        VisualEditor.DataRow defaultValue = edfCtrlr.getDefaultValue();

        System.assert(defaultValue!=null);

        Test.stopTest();

    }
    
}